import "./left-panel.js";
import "./header.js";
import "./platform-calendar.js";
import "./platform-leads.js";
import "./platform-leads-popups.js";
import "./platform-student.js";
import "./course.js";
import "./courses-grid.js";
import "./lesson.js";